//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP
    {
        public int A_ID { get; set; }
        public string A_NAME { get; set; }
        public Nullable<int> A_PARENT { get; set; }
        public string A_ABBR { get; set; }
        public int A_ACTIVE { get; set; }
        public Nullable<int> A_T_TYPE { get; set; }
        public Nullable<int> CLASS_ID { get; set; }
    }
}
