//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT_DATATYPE
    {
        public int DT_ID { get; set; }
        public string DT_DESCR { get; set; }
        public string DT_ACRONYM { get; set; }
        public string DT_TYPE { get; set; }
        public Nullable<int> CLASS_ID { get; set; }
    }
}
