//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDITS4INTERNAL
    {
        public long AD_ID { get; set; }
        public int AD_DATATYPE_ID { get; set; }
        public int AD_DATA_ID { get; set; }
        public int AD_TRAN_ID { get; set; }
        public System.DateTime AD_TIMESTAMP { get; set; }
        public int AD_POC_ID { get; set; }
        public string AD_COMMENT { get; set; }
        public Nullable<int> CLASS_ID { get; set; }
    }
}
