//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class AWARENESS
    {
        public int A_ID { get; set; }
        public string A_LEVEL { get; set; }
        public double A_ORDER { get; set; }
        public short A_MIN_AWARE { get; set; }
        public Nullable<int> CLASS_ID { get; set; }
    }
}
