//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMAND
    {
        public int COMMAND_ID { get; set; }
        public string COMMAND1 { get; set; }
        public string TYPE { get; set; }
        public string ACRONYM { get; set; }
    }
}
