//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_SERVICE
    {
        public int CS_ID { get; set; }
        public int CS_C_ID { get; set; }
        public int CS_S_ID { get; set; }
    }
}
