//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT_INFO
    {
        public int CI_ID { get; set; }
        public string E_ADDRESS { get; set; }
        public string PHONE_DSN { get; set; }
        public string PHONE_COMM { get; set; }
        public string PHONE_TOLL_FREE { get; set; }
    }
}
