//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_TEMPLATES
    {
        public int ETP_ID { get; set; }
        public string ETP_ACRONYM { get; set; }
        public string ETP_SUBJECT { get; set; }
        public string ETP_BODY { get; set; }
        public Nullable<int> ETP_TYPE { get; set; }
    }
}
