//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_EMAILS
    {
        public long GE_ID { get; set; }
        public string GE_FROM { get; set; }
        public string GE_TO { get; set; }
        public string GE_CC { get; set; }
        public string GE_SUBJECT { get; set; }
        public string GE_BODY { get; set; }
        public Nullable<int> GE_DISABLED { get; set; }
        public Nullable<int> GE_TYPE { get; set; }
        public Nullable<System.DateTime> GE_TIMESTAMP { get; set; }
        public Nullable<int> GE_DATA_ID { get; set; }
    }
}
