//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class IASO
    {
        public int IA_ID { get; set; }
        public Nullable<int> IA_POC_ID { get; set; }
        public Nullable<short> IA_TYPE { get; set; }
        public string IA_LOGIN { get; set; }
        public Nullable<int> IA_ACTIVITY { get; set; }
        public Nullable<System.DateTime> IA_APPT { get; set; }
        public Nullable<System.DateTime> IA_EXPIRE { get; set; }
        public Nullable<short> IA_LETTER { get; set; }
        public Nullable<System.DateTime> IA_LAST_UPD { get; set; }
        public Nullable<int> IA_LAST_UPD_BY { get; set; }
        public Nullable<int> IA_STATUS { get; set; }
    }
}
