//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITSM_SITES
    {
        public string IT_ID { get; set; }
        public string IT_NAME { get; set; }
        public string IT_CITY { get; set; }
        public string IT_STATE { get; set; }
        public string IT_COUNTRY { get; set; }
    }
}
