//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {
        public int LOCATION_ID { get; set; }
        public string LOCATION1 { get; set; }
        public string STATE { get; set; }
        public Nullable<decimal> LATITUDE { get; set; }
        public Nullable<decimal> LONGITUDE { get; set; }
        public Nullable<short> REGION_ID { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<int> L_TZ_ID { get; set; }
        public Nullable<short> NETCOPTYPE { get; set; }
        public Nullable<int> L_F_ID { get; set; }
        public Nullable<int> L_INSTALLATION_TYPE { get; set; }
    }
}
