//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATION
    {
        public int NOTIFY_ID { get; set; }
        public System.DateTime NOTIFY_START_DATE { get; set; }
        public System.DateTime NOTIFY_EXPIRATION_DATE { get; set; }
        public string NOTIFY_TITLE { get; set; }
        public string NOTIFY_TEXT { get; set; }
        public string NOTIFY_IMAGE { get; set; }
        public int NOTIFY_STICKY { get; set; }
        public Nullable<int> NOTIFY_DURATION { get; set; }
        public string NOTIFY_CLASS_NAME { get; set; }
        public string NOTIFY_BEFORE_OPEN_FN { get; set; }
        public string NOTIFY_AFTER_OPEN_FN { get; set; }
        public string NOTIFY_BEFORE_CLOSE_FN { get; set; }
        public string NOTIFY_AFTER_CLOSE_FN { get; set; }
        public int NOTIFY_ACTIVE { get; set; }
        public int NOTIFY_DND { get; set; }
    }
}
