//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORG
    {
        public int O_ID { get; set; }
        public string O_ORG { get; set; }
        public string O_ACRONYM { get; set; }
        public int O_PARENTORG { get; set; }
        public Nullable<int> O_TIER { get; set; }
        public Nullable<int> O_APP_ID { get; set; }
        public int O_ISDELETE { get; set; }
        public int O_PARENT { get; set; }
        public Nullable<int> O_POPCON_ESC { get; set; }
        public Nullable<int> O_POPCON_CONCUR { get; set; }
        public Nullable<int> O_AWARE_ID { get; set; }
        public string O_ICON { get; set; }
        public Nullable<int> O_PADCON { get; set; }
        public string O_EMAIL { get; set; }
        public string O_SUPPORT_CO { get; set; }
        public string O_PHONE_CMCL { get; set; }
        public string O_PHONE_DSN { get; set; }
        public string O_PHONE_TOLLFREE { get; set; }
        public Nullable<short> O_IS_ORG_WORKING_RESOLVED { get; set; }
    }
}
