//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORG_EMAIL_TEMPLATE
    {
        public int OET_ID { get; set; }
        public Nullable<int> OET_O_ID { get; set; }
        public Nullable<int> OET_S_ID { get; set; }
        public Nullable<int> OET_T_ID { get; set; }
    }
}
