//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGS_LOCATIONS
    {
        public int OL_ID { get; set; }
        public int OL_ORG_ID { get; set; }
        public int OL_LOCATION_ID { get; set; }
        public int OL_ACTY_LOC_ID { get; set; }
        public int OL_ISNETCOP { get; set; }
        public string OL_DISPLAY { get; set; }
        public string OL_ITSM_ID { get; set; }
        public Nullable<int> OL_THE_ID { get; set; }
    }
}
