//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWNER
    {
        public int OWNER_ID { get; set; }
        public string OWNER1 { get; set; }
        public string OWNEREML { get; set; }
        public Nullable<int> ORG_ID { get; set; }
        public Nullable<int> O_ORG_LOC { get; set; }
        public string OWNER_ABBR { get; set; }
        public Nullable<int> O_THE_ID { get; set; }
    }
}
