//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class POC
    {
        [DisplayName("ID: ")]
        public int POC_ID { get; set; }
        [DisplayName("Last: ")]
        public string POC_LAST { get; set; }
        [DisplayName("First: ")]
        public string POC_FIRST { get; set; }
        [DisplayName("Middle: ")]
        public string POC_MI { get; set; }
        public Nullable<int> RANK { get; set; }
        public Nullable<int> ORG_LOC { get; set; }
        public string AKO_LOGIN { get; set; }
        [DisplayName("NIPR: ")]
        public string EMAIL { get; set; }
        [DisplayName("SIPR: ")]
        public string SEMAIL { get; set; }
        public string ALT_EMAIL { get; set; }
        [DisplayName("EDIPI: ")]
        public long CAC_EDIPI { get; set; }
        [DisplayName("DSN #: ")]
        public string PHONE_DSN { get; set; }
        [DisplayName("COM #: ")]
        public string PHONE_COMM { get; set; }
        [DisplayName("CELL #: ")]
        public string PHONE_EMERG { get; set; }
        public Nullable<System.DateTime> LAST_VERIFIED { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public Nullable<int> LAST_UPDATE_BY { get; set; }
        public string POC_AVATAR { get; set; }
        public int COMPANY_ID { get; set; }
        public Nullable<System.DateTime> CAC_EDIPI_LAST_UPDATE { get; set; }
        public short OVERRIDE_EMAIL_UPDATE { get; set; }
        public Nullable<System.DateTime> LAST_LOGIN { get; set; }
        public int DAYS_LAST_LOGIN { get; set; }

        [DisplayName("NAME: ")]
        public string FullName { get { return string.Format("{0} {1} {2}", POC_FIRST, POC_MI, POC_LAST); } }
    }
}
