//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREFERENCE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PREFERENCE()
        {
            this.PREFERENCE_THEATER_VALUES = new HashSet<PREFERENCE_THEATER_VALUES>();
        }
    
        public int P_ID { get; set; }
        public string P_DESCRIPTION { get; set; }
        public int P_PT_ID { get; set; }
        public int P_PV_ID { get; set; }
        public int P_PARENT { get; set; }
        public int P_THE_ID { get; set; }
        public Nullable<int> P_DEFAULT { get; set; }
        public string P_HTML_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PREFERENCE_THEATER_VALUES> PREFERENCE_THEATER_VALUES { get; set; }
    }
}
