//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class RANK
    {
        public int RANK_ID { get; set; }
        public string RANK1 { get; set; }
        public string TITLE { get; set; }
        public Nullable<short> TYPE { get; set; }
        public Nullable<short> TYPE_ORDER { get; set; }
    }
}
