//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESTDEMO
    {
        public int POC_ID { get; set; }
        public int RD_NUMBER { get; set; }
        public string RD_VARCHAR2 { get; set; }
        public Nullable<System.DateTime> RD_DATE { get; set; }
        public string RD_CLOB { get; set; }
    }
}
