//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_ELE_TRAINING
    {
        public int RPT_ELE_ID { get; set; }
        public int TRAIN_ID { get; set; }
    
        public virtual RPT_ELE RPT_ELE { get; set; }
    }
}
