//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDDATE
    {
        public int SCHEDDATEID { get; set; }
        public Nullable<int> TRAINID { get; set; }
        public Nullable<int> EDIPI { get; set; }
        public Nullable<System.DateTime> DATESCHED { get; set; }
        public string TRAINTITLE { get; set; }
        public Nullable<int> DATETIMEID { get; set; }
    }
}
