//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE_EMAIL
    {
        public int E_ID { get; set; }
        public int E_S_ID { get; set; }
        public string E_TYPE { get; set; }
        public string E_ADDRESS { get; set; }
    }
}
