//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE
    {
        public int S_ID { get; set; }
        public string S_SERVICE { get; set; }
        public string S_ABBR { get; set; }
        public Nullable<int> DUPREMOVE { get; set; }
    }
}
