//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAM
    {
        public int T_ID { get; set; }
        public string TEAM1 { get; set; }
        public int T_PARENT { get; set; }
        public Nullable<int> NUMMBRS { get; set; }
        public string T_EMAIL { get; set; }
        public Nullable<int> ID_OLD { get; set; }
        public double STATUS_ID { get; set; }
    }
}
