//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class THEATER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THEATER()
        {
            this.PREFERENCE_THEATER_VALUES = new HashSet<PREFERENCE_THEATER_VALUES>();
        }
    
        public int T_ID { get; set; }
        public Nullable<int> T_ORG { get; set; }
        public string T_NAME { get; set; }
        public Nullable<int> POND_POC { get; set; }
        public Nullable<decimal> MAP_LAT { get; set; }
        public Nullable<decimal> MAP_LNG { get; set; }
        public Nullable<int> MAP_ZOOM { get; set; }
        public Nullable<int> CON_ORG { get; set; }
        public string T_LOGO { get; set; }
        public string T_ABBR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PREFERENCE_THEATER_VALUES> PREFERENCE_THEATER_VALUES { get; set; }
    }
}
