//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class THEATERTIMEZONE
    {
        public int ID_THEATZ { get; set; }
        public Nullable<int> THEATER_ID { get; set; }
        public Nullable<int> TIMEZONE_ID { get; set; }
        public Nullable<int> DISPLAY_ORDER { get; set; }
    }
}
