//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMEZONE
    {
        public int TZ_ID { get; set; }
        public string GMT_OFFSET { get; set; }
        public string TIMEZONE1 { get; set; }
        public string TMZONE_ABBREV { get; set; }
        public string TMZONE_REF { get; set; }
        public string TMZONE_IMG { get; set; }
        public Nullable<int> DST { get; set; }
        public string TIMEZONE_ALIAS { get; set; }
    }
}
