//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRAINING()
        {
            this.USERDATES = new HashSet<USERDATE>();
        }
    
        public int TRAIN_ID { get; set; }
        public string TRAIN_TITLE { get; set; }
        public string TRAIN_DETAILS { get; set; }
        public string TYPE { get; set; }
        public string FREQUENCY { get; set; }
        public Nullable<int> CLASS_DUR { get; set; }
        public string MIN_ATTEND { get; set; }
        public string MAX_ATTEND { get; set; }
        public string ATCTS { get; set; }
        public string MANDATED_BY { get; set; }
        public string URL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERDATE> USERDATES { get; set; }
    }
}
