//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAIN_DATE_TIME
    {
        public int DATE_TIME_ID { get; set; }
        public Nullable<System.DateTime> TRAIN_DATE_TIME1 { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public Nullable<System.DateTime> DATE_TAKEN { get; set; }
        public string LOC { get; set; }
        public Nullable<int> TRAIN_ID { get; set; }
        public string TRAIN_TITLE { get; set; }
    }
}
