//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PA_COMMON : DbContext
    {
        public PA_COMMON()
            : base("name=PA_COMMON")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APP> APPS { get; set; }
        public virtual DbSet<AUDIT_COMMENT> AUDIT_COMMENT { get; set; }
        public virtual DbSet<AUDIT_DATATYPE> AUDIT_DATATYPE { get; set; }
        public virtual DbSet<AUDIT_TRANS> AUDIT_TRANS { get; set; }
        public virtual DbSet<AUDIT> AUDITS { get; set; }
        public virtual DbSet<AUDITS4INTERNAL> AUDITS4INTERNAL { get; set; }
        public virtual DbSet<AWARENESS> AWARENESSes { get; set; }
        public virtual DbSet<CLASSIFICATION> CLASSIFICATIONs { get; set; }
        public virtual DbSet<COMMAND> COMMANDS { get; set; }
        public virtual DbSet<COMPANY> COMPANies { get; set; }
        public virtual DbSet<COMPANY_RANK_TYPE> COMPANY_RANK_TYPE { get; set; }
        public virtual DbSet<COMPANY_TYPE> COMPANY_TYPE { get; set; }
        public virtual DbSet<CONFIG> CONFIGs { get; set; }
        public virtual DbSet<CONST> CONSTs { get; set; }
        public virtual DbSet<CONTACT_INFO> CONTACT_INFO { get; set; }
        public virtual DbSet<CONTACT_TYPE> CONTACT_TYPE { get; set; }
        public virtual DbSet<COUNTRy> COUNTRIES { get; set; }
        public virtual DbSet<EMAIL_SALUTATIONS> EMAIL_SALUTATIONS { get; set; }
        public virtual DbSet<EMAIL_TEMPLATES> EMAIL_TEMPLATES { get; set; }
        public virtual DbSet<EMAIL_TYPE> EMAIL_TYPE { get; set; }
        public virtual DbSet<FAD> FADs { get; set; }
        public virtual DbSet<GEN_EMAILS> GEN_EMAILS { get; set; }
        public virtual DbSet<IASO> IASOes { get; set; }
        public virtual DbSet<INSTALLATION_TYPE> INSTALLATION_TYPE { get; set; }
        public virtual DbSet<ITSM_SITES> ITSM_SITES { get; set; }
        public virtual DbSet<LOCATION> LOCATIONS { get; set; }
        public virtual DbSet<MACOM> MACOMS { get; set; }
        public virtual DbSet<NOTIFICATION> NOTIFICATIONS { get; set; }
        public virtual DbSet<ORG_CONTACT_INFO> ORG_CONTACT_INFO { get; set; }
        public virtual DbSet<ORG_EMAIL_TEMPLATE> ORG_EMAIL_TEMPLATE { get; set; }
        public virtual DbSet<ORG> ORGS { get; set; }
        public virtual DbSet<ORGS_LOCATIONS> ORGS_LOCATIONS { get; set; }
        public virtual DbSet<ORGS_WORKING> ORGS_WORKING { get; set; }
        public virtual DbSet<ORGS_WORKING_THEATER> ORGS_WORKING_THEATER { get; set; }
        public virtual DbSet<OWNER> OWNERs { get; set; }
        public virtual DbSet<POC> POCS { get; set; }
        public virtual DbSet<POCS_ACCT> POCS_ACCT { get; set; }
        public virtual DbSet<POCS_PREFERENCES> POCS_PREFERENCES { get; set; }
        public virtual DbSet<PREFERENCE_THEATER_VALUES> PREFERENCE_THEATER_VALUES { get; set; }
        public virtual DbSet<PREFERENCE_TYPE> PREFERENCE_TYPE { get; set; }
        public virtual DbSet<PREFERENCE_VALUES> PREFERENCE_VALUES { get; set; }
        public virtual DbSet<PREFERENCE> PREFERENCES { get; set; }
        public virtual DbSet<RANK_TYPE> RANK_TYPE { get; set; }
        public virtual DbSet<RANK> RANKS { get; set; }
        public virtual DbSet<REGION> REGIONS { get; set; }
        public virtual DbSet<RESTDEMO> RESTDEMOes { get; set; }
        public virtual DbSet<SERVICE_EMAIL> SERVICE_EMAIL { get; set; }
        public virtual DbSet<SERVICE_OWNER> SERVICE_OWNER { get; set; }
        public virtual DbSet<SERVICE_TYPE> SERVICE_TYPE { get; set; }
        public virtual DbSet<SERVICE> SERVICES { get; set; }
        public virtual DbSet<STATUS> STATUS { get; set; }
        public virtual DbSet<TEAM> TEAMS { get; set; }
        public virtual DbSet<TEAMS_LOD_MAP> TEAMS_LOD_MAP { get; set; }
        public virtual DbSet<TEAMS_STATUS> TEAMS_STATUS { get; set; }
        public virtual DbSet<THEATER> THEATERS { get; set; }
        public virtual DbSet<THEATERS_SERVICES> THEATERS_SERVICES { get; set; }
        public virtual DbSet<THEATERTIMEZONE> THEATERTIMEZONEs { get; set; }
        public virtual DbSet<TIMEZONE> TIMEZONES { get; set; }
        public virtual DbSet<VOTE> VOTEs { get; set; }
        public virtual DbSet<COMPANY_SERVICE> COMPANY_SERVICE { get; set; }
        public virtual DbSet<EMAIL_EXT> EMAIL_EXT { get; set; }
        public virtual DbSet<NOTIFICATIONS_DND> NOTIFICATIONS_DND { get; set; }
        public virtual DbSet<VIEW_POCS_ALL> VIEW_POCS_ALL { get; set; }
    }
}
