//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTrainingData
    {
        public int TRAINID { get; set; }
        public string TRAIN_TITLE { get; set; }
        public string TYPE { get; set; }
        public string FREQUENCY { get; set; }
        public string REQ_NAME { get; set; }
        public string RPT_ELE_NAME { get; set; }
        public string TRAIN_DETAILS { get; set; }
        public string ATCTS { get; set; }
        public string MANDATED_BY { get; set; }
        public string URL { get; set; }
        public int REQ_ID { get; set; }
        public int RPT_ELE_ID { get; set; }
        public Nullable<int> CLASS_DUR { get; set; }
    }
}
